language: python
dist: xenial
python:
  - 3.6
  - 3.7
install:
  - curl -fsSL -o mutagen.tar.gz https://github.com/havoc-io/mutagen/releases/download/v0.9.2/mutagen_linux_amd64_v0.9.2.tar.gz
  - mkdir mutagen && tar zxvf mutagen.tar.gz -C /home/travis/bin
  - mutagen daemon start
  - pip install pip --upgrade
  - pip install -e .[dev,test] --upgrade
  - pip install pytest --upgrade
  - pip install flake8
  - pip install coveralls
  - pytest --version
script:
  - flake8 mutagen_helper
  - coverage run --source=mutagen_helper setup.py test
  - python setup.py build
after_success:
  - coveralls